# Generated by Django 5.0.6 on 2024-06-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=50)),
                ('createdBy', models.CharField(max_length=50)),
                ('assignedTo', models.CharField(max_length=50)),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
            ],
            options={
                'db_table': 'createtask',
            },
        ),
    ]
