# Generated by Django 5.0.6 on 2024-06-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createtask',
            name='enddate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='createtask',
            name='startdate',
            field=models.DateField(),
        ),
    ]
